/**
 * This file will automatically be loaded by electron and run in the "main" context.
 * This is your "backend"
 * To learn more about the differences between the "main" and the "renderer" context in
 * Electron, visit:
 *
 * https://electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes
 */

 import { app, BrowserWindow } from "electron";
 import isDev from "electron-is-dev";
 import Store from "electron-persist-secure/lib/store";
 // Import all IPCs to make sure they register their respective listeners
 import "./app/ipc/main";
 import { spawnBrowser, spawnImpervious, checkForDaemonUpdates, initDownloadInfo } from "./module";
 import unhandled from "electron-unhandled";
 import log from "electron-log";
 import os from "os";
 // import "./app/ipc/anything";
 
 // This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
 // plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
 // whether you're running in development or production).
 // TODO: This may not be the best way to do this
 declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
 declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
 
 // global exception handler
 unhandled({
   logger: () => log.error(),
 });
 
 // Handle creating/removing shortcuts on Windows when installing/uninstalling.
 if (require("electron-squirrel-startup")) {
   // eslint-disable-line global-require
   app.quit();
 }
 
 // Make sure to call this ONCE.
 const createStores = (): void => {
   new Store({
     configName: "config", // The stores name
   });
 };
 
 export const createWindow = (): void => {
   // Create the browser window.
   const mainWindow = new BrowserWindow({
     height: 720,
     width: 1280,
     webPreferences: {
       contextIsolation: true,
       nodeIntegration: false,
       preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
     },
     // to disable the top bar / frame completely uncomment the next line -
     // if you do this you will have to set up a css class to allow certain parts of your app to be "draggable"
 
     // frame: false
   });
 
   // and load the index.html of the app.
   mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
 
   // Open the DevTools if in dev.
   if (isDev) {
     mainWindow.webContents.openDevTools();
   }
 };
 
 const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
  app.quit()
}

 // This method will be called when Electron has finished
 // initialization and is ready to create browser windows.
 // Some APIs can only be used after this event occurs.
 app.on("ready", async () => {
   createStores();
   // createWindow();
   // console.log("[INFO] Checking for updates");
   await initDownloadInfo();
   // await checkForDaemonUpdates();
   console.log("[INFO] Spawning the impervious daemon");
   await spawnImpervious();
   console.log("[INFO] Spawning the impervious browser");
   await spawnBrowser();
   if (os.platform() === "darwin") {
     app.dock.hide();
   }
 });
 
 // Quit when all windows are closed, except on macOS. There, it's common
 // for applications and their menu bar to stay active until the user quits
 // explicitly with Cmd + Q.
 app.on("window-all-closed", () => {
   if (process.platform !== "darwin" && process.platform !== "linux") { // also, we dont want electron to die on linux either as it triggers 'before-quit' section below where all pids are killed. May not want this for windows in the future either..
     app.quit();
   }
 });
 
 export const pids: Array<number> = []; // holds pids of daemon and browser window so we can kill them later
 
 app.on("before-quit", () => {
   // when browser closes, it will fire close(). this will kill daemon and ensure daemon always dies when electron or firefox goes away
     console.info("Pids in list: ", pids);
     pids.forEach((pid) => {
      try {
       process.kill(pid);
      } catch (error) {
        console.error("Error in PID deletion: ", error.message);
      }
     });
 });
 
 app.on("activate", () => {
   // On OS X it's common to re-create a window in the app when the
   // dock icon is clicked and there are no other windows open.
  //  if (BrowserWindow.getAllWindows().length === 0) {
  //    createWindow();
  //  }
 });